-- modules/fluid_topology.lua
-- Custom topology layout manager for fluid network visualization.
--
-- Manages a persistent 2D grid layout for the topology display mode.
-- Elements are placed on a grid where each cell can hold one element node.
--
-- On first discovery (no saved layout), an auto-layout is generated from
-- scan data (elements sorted by location within each network).
-- The layout can then be customized via:
--   - Network bus commands (topo_set_node, topo_remove_node, topo_move_node)
--   - Future: interactive edit mode on screen
--
-- Layout structure:
-- {
--   version = 1,
--   grid = {
--     [networkId] = {
--       label = "Network #1 [Water]",
--       nodes = {
--         { elementId = "abc-123", gridX = 0, gridY = 0 },
--         { elementId = "def-456", gridX = 1, gridY = 0 },
--       },
--       connections = {
--         { from = "abc-123", to = "def-456" },
--       },
--     },
--   },
--   orphans = {  -- elements not in any network
--     { elementId = "ghi-789", gridX = 0, gridY = 0 },
--   },
-- }
--
-- Persistence: saved as a Lua table file on the computer filesystem.

local FluidTopology = {}

-- ============================================================================
-- State
-- ============================================================================

local layout = nil       -- current layout table
local layoutFilePath = nil
local dirty = false      -- unsaved changes flag
local autoGenerated = false -- true if layout was auto-generated (not yet saved by user)

-- ============================================================================
-- Initialization
-- ============================================================================

--- Initialize the topology manager.
-- @param options table - { filePath }
function FluidTopology.init(options)
  options = options or {}
  layoutFilePath = options.filePath or nil

  if layoutFilePath then
    FluidTopology.load()
  end

  if layout then
    print("[FLUID_TOPO] Loaded custom topology layout")
  else
    print("[FLUID_TOPO] No layout found - will auto-generate on first scan")
  end
end

-- ============================================================================
-- Persistence
-- ============================================================================

--- Simple table serializer (same as fluid_rules).
local function serializeTable(t, indent)
  indent = indent or 0
  local pad = string.rep("  ", indent)
  local pad1 = string.rep("  ", indent + 1)
  local parts = {}

  if #t > 0 then
    table.insert(parts, "{\n")
    for i, v in ipairs(t) do
      local comma = (i < #t) and ",\n" or "\n"
      if type(v) == "table" then
        table.insert(parts, pad1 .. serializeTable(v, indent + 1) .. comma)
      elseif type(v) == "string" then
        table.insert(parts, pad1 .. '"' .. v:gsub('"', '\\"') .. '"' .. comma)
      elseif type(v) == "boolean" then
        table.insert(parts, pad1 .. tostring(v) .. comma)
      else
        table.insert(parts, pad1 .. tostring(v) .. comma)
      end
    end
    table.insert(parts, pad .. "}")
  else
    table.insert(parts, "{\n")
    local keys = {}
    for k in pairs(t) do table.insert(keys, k) end
    table.sort(keys, function(a, b) return tostring(a) < tostring(b) end)
    for i, k in ipairs(keys) do
      local v = t[k]
      local comma = (i < #keys) and ",\n" or "\n"
      local keyStr = '["' .. tostring(k) .. '"]'
      if type(v) == "table" then
        table.insert(parts, pad1 .. keyStr .. " = " .. serializeTable(v, indent + 1) .. comma)
      elseif type(v) == "string" then
        table.insert(parts, pad1 .. keyStr .. ' = "' .. v:gsub('"', '\\"') .. '"' .. comma)
      elseif type(v) == "boolean" then
        table.insert(parts, pad1 .. keyStr .. " = " .. tostring(v) .. comma)
      else
        table.insert(parts, pad1 .. keyStr .. " = " .. tostring(v) .. comma)
      end
    end
    table.insert(parts, pad .. "}")
  end

  return table.concat(parts)
end

--- Save layout to filesystem.
function FluidTopology.save()
  if not layoutFilePath or not layout then return false end

  local content = "return " .. serializeTable(layout)
  local ok, err = pcall(function()
    -- Ensure the data directory exists
    local dir = layoutFilePath:match("(.+)/[^/]+$")
    if dir then pcall(function() filesystem.createDir(dir, true) end) end
    local file = filesystem.open(layoutFilePath, "w")
    if not file then error("Failed to open file for writing: " .. layoutFilePath) end
    file:write(content)
    file:close()
  end)

  if ok then
    dirty = false
    autoGenerated = false
    print("[FLUID_TOPO] Layout saved to " .. layoutFilePath)
  else
    print("[FLUID_TOPO] Save failed: " .. tostring(err))
  end
  return ok
end

--- Load layout from filesystem.
function FluidTopology.load()
  if not layoutFilePath then return false end

  local ok, data = pcall(function()
    return filesystem.doFile(layoutFilePath)
  end)

  if ok and data and data.version then
    layout = data
    autoGenerated = false
    dirty = false
    return true
  end

  layout = nil
  return false
end

-- ============================================================================
-- Auto-layout generation
-- ============================================================================

--- Generate an automatic topology layout from scan data.
-- Elements within each network are placed left-to-right on a single row,
-- sorted by their X location. This serves as a starting point for the user
-- to customize.
-- @param scanResult table - full scan result from FluidScanner.scan()
-- @return table - the generated layout
function FluidTopology.autoGenerate(scanResult)
  if not scanResult then return nil end

  local newLayout = {
    version = 1,
    grid = {},
    orphans = {},
  }

  -- Build network layouts
  local netList = {}
  for nid, netData in pairs(scanResult.networks) do
    table.insert(netList, { id = nid, data = netData })
  end
  table.sort(netList, function(a, b) return a.id < b.id end)

  for _, net in ipairs(netList) do
    local fluidLabel = net.data.fluidType and net.data.fluidType.name or "Unknown"
    local netLayout = {
      label = "Network #" .. tostring(net.id) .. " [" .. fluidLabel .. "]",
      nodes = {},
      connections = {},
    }

    -- Elements are already sorted by location X in scan()
    for i, elem in ipairs(net.data.elements) do
      table.insert(netLayout.nodes, {
        elementId = elem.id,
        gridX = (i - 1) % 6,
        gridY = math.floor((i - 1) / 6),
      })

      -- Auto-connect sequential elements
      if i > 1 then
        table.insert(netLayout.connections, {
          from = net.data.elements[i - 1].id,
          to = elem.id,
        })
      end
    end

    newLayout.grid[tostring(net.id)] = netLayout
  end

  -- Orphans (elements not in any network)
  for _, e in ipairs(scanResult.elements) do
    if not e.networkIDs or #e.networkIDs == 0 then
      local idx = #newLayout.orphans
      table.insert(newLayout.orphans, {
        elementId = e.id,
        gridX = idx % 6,
        gridY = math.floor(idx / 6),
      })
    end
  end

  layout = newLayout
  autoGenerated = true
  dirty = true

  print("[FLUID_TOPO] Auto-generated layout: " ..
    #netList .. " networks, " .. #newLayout.orphans .. " orphans")
  return layout
end

-- ============================================================================
-- Layout access
-- ============================================================================

--- Get the current layout (auto-generates if none exists).
-- @param scanResult table - needed for auto-generation
-- @return table|nil
function FluidTopology.getLayout(scanResult)
  if not layout and scanResult then
    FluidTopology.autoGenerate(scanResult)
  end
  return layout
end

--- Check if the layout was auto-generated (not yet user-customized).
-- @return boolean
function FluidTopology.isAutoGenerated()
  return autoGenerated
end

--- Check if there are unsaved changes.
-- @return boolean
function FluidTopology.isDirty()
  return dirty
end

-- ============================================================================
-- Layout modification (CRUD for nodes and connections)
-- ============================================================================

--- Set a node's grid position within a network.
-- @param networkId string
-- @param elementId string
-- @param gridX number
-- @param gridY number
-- @return boolean
function FluidTopology.setNodePosition(networkId, elementId, gridX, gridY)
  if not layout then return false end

  local netKey = tostring(networkId)
  local netLayout = layout.grid[netKey]
  if not netLayout then
    -- Create network entry if it doesn't exist
    netLayout = { label = "Network #" .. netKey, nodes = {}, connections = {} }
    layout.grid[netKey] = netLayout
  end

  -- Find existing node or insert new
  for _, node in ipairs(netLayout.nodes) do
    if node.elementId == elementId then
      node.gridX = gridX
      node.gridY = gridY
      dirty = true
      return true
    end
  end

  -- Not found: add new node
  table.insert(netLayout.nodes, {
    elementId = elementId,
    gridX = gridX,
    gridY = gridY,
  })
  dirty = true
  return true
end

--- Remove a node from the layout (it will use auto-position on next render).
-- @param networkId string
-- @param elementId string
-- @return boolean
function FluidTopology.removeNode(networkId, elementId)
  if not layout then return false end
  local netLayout = layout.grid[tostring(networkId)]
  if not netLayout then return false end

  for i, node in ipairs(netLayout.nodes) do
    if node.elementId == elementId then
      table.remove(netLayout.nodes, i)
      dirty = true
      return true
    end
  end
  return false
end

--- Add a connection between two elements.
-- @param networkId string
-- @param fromId string
-- @param toId string
-- @return boolean
function FluidTopology.addConnection(networkId, fromId, toId)
  if not layout then return false end
  local netLayout = layout.grid[tostring(networkId)]
  if not netLayout then return false end

  -- Check for existing connection
  for _, conn in ipairs(netLayout.connections) do
    if conn.from == fromId and conn.to == toId then
      return true -- already exists
    end
  end

  table.insert(netLayout.connections, { from = fromId, to = toId })
  dirty = true
  return true
end

--- Remove a connection between two elements.
-- @param networkId string
-- @param fromId string
-- @param toId string
-- @return boolean
function FluidTopology.removeConnection(networkId, fromId, toId)
  if not layout then return false end
  local netLayout = layout.grid[tostring(networkId)]
  if not netLayout then return false end

  for i, conn in ipairs(netLayout.connections) do
    if conn.from == fromId and conn.to == toId then
      table.remove(netLayout.connections, i)
      dirty = true
      return true
    end
  end
  return false
end

--- Reset the layout (force auto-regeneration on next scan).
function FluidTopology.reset()
  layout = nil
  autoGenerated = false
  dirty = false
  print("[FLUID_TOPO] Layout reset - will auto-generate on next scan")
end

--- Export the current layout as a table (for network bus transmission).
-- @return table|nil
function FluidTopology.export()
  return layout
end

--- Import a layout from a table (from network bus or file).
-- @param data table
-- @return boolean
function FluidTopology.import(data)
  if not data or not data.version then return false end
  layout = data
  autoGenerated = false
  dirty = true
  return true
end

return FluidTopology
